"""Constants for EIRC Integration."""

from typing import Final

DOMAIN: Final = "eirc"
API_AUTH_URL: Final = "https://ikus.pesc.ru/api/v8/users/auth"
API_ACCOUNTS_URL: Final = "https://ikus.pesc.ru/api/v8/accounts"
SERVICE_SEND_METER_READING: Final = "send_meter_reading"
ATTR_ENTITY_ID: Final = "entity_id"
ATTR_READINGS: Final = "readings"

CONF_USERNAME: Final = "username"
CONF_PASSWORD: Final = "password"
CONF_SELECTED_ACCOUNTS: Final = "selected_accounts"
CONF_USE_PROXY: Final = "use_proxy"
CONF_PROXY_URL: Final = "proxy_url"
CONF_SESSION_COOKIE: Final = "session_cookie"
CONF_TOKEN_AUTH: Final = "token_auth"
CONF_TOKEN_VERIFY: Final = "token_verify"

ERROR_INVALID_AUTH: Final = "invalid_auth"
ERROR_CANNOT_CONNECT: Final = "cannot_connect"
ERROR_INVALID_PROXY_URL: Final = "invalid_proxy_url"
ERROR_PROXY_URL_REQUIRED: Final = "proxy_url_required"
ERROR_INVALID_CODE: Final = "invalid_code"
ERROR_NO_VALID_ACCOUNTS: Final = "no_valid_accounts"
ERROR_2FA_METHOD_NOT_SUPPORTED: Final = "2fa_method_not_supported"
ERROR_2FA_SEND_FAILED: Final = "2fa_send_failed"
ERROR_ENTRY_NOT_FOUND: Final = "entry_not_found"
ERROR_REAUTH_SUCCESSFUL: Final = "reauth_successful"
ERROR_UNKNOWN: Final = "unknown"
ERROR_CANNOT_FETCH_ACCOUNTS: Final = "cannot_fetch_accounts"
