"""Constants for EIRC Integration."""

DOMAIN = "eirc"
API_AUTH_URL = "https://ikus.pesc.ru/api/v8/users/auth"
API_ACCOUNTS_URL = "https://ikus.pesc.ru/api/v8/accounts"
SERVICE_SEND_METER_READING = "send_meter_reading"
ATTR_ENTITY_ID = "entity_id"
ATTR_READINGS = "readings"
CONF_PROXY_URL = "proxy_url"
CONF_PROXY_TYPE = "proxy_type"
